In [0]:
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).

In [0]:
import pandas as pd

In [0]:
# 데이터 정리

def handling(data):
    # 불필요한 부분 자르기
    col1 = list(data.iloc[2])
    pre_data = data.iloc[3:, :]
    pre_data.columns = col1
    
    # 전체 요일만 추려서 연도로 바꿔주기
    re_data = pre_data[['월', '모든요일']]
    re_data.columns = ['월', '2011년', '2012년', '2013년', '2014년', '2015년', '2016년', '2017년', '2018년']
    
    # 데이터 타입 변경
    col2 = list(re_data.columns)
    series = [re_data['월']] # pd.to_numeric을 위한 시리즈 분리
    for year in col2: # 분리한 시리즈 들의 데이터 타입 변경
        if year != '월':
            series.append(pd.to_numeric(re_data[year]))
    
    # 분리한 시리즈들 다시 합치기
    num_data = pd.concat([series[0], series[1]], axis=1)
    for i in range(2, len(series)):
        num_data = pd.concat([num_data, series[i]], axis=1)
    
    return num_data

In [0]:
def arrange(data):
    date = []
    district = []
    avg_people = []
    
    for year in years:
        for i in range(len(num_list)):
            # 해당 년도, 월의 평균 지하철 이용 수
            # 반올림
            avg = round(data[data['월']==str(num_list[i])+'월'][year].mean(), 1)

            date.append("{}{:02d}월".format(year, num_list[i]))
            district.append(reg)
            avg_people.append(avg)
            
    return pd.DataFrame(data={"기간": date, "자치구": district, "승하차 평균": avg_people}, columns=["기간", "자치구", "승하차 평균"])

In [0]:
num_list = list(range(1, 13))
years = ['2011년', '2012년', '2013년', '2014년', '2015년', '2016년', '2017년', '2018년']
region = ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', 
          '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구']

In [0]:
# 정리한 데이터들 저장

reg_frame = []

In [0]:
data0 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/강남구.csv', na_values='-')
reg = region[0]

data0 = handling(data0)
gang_nam = arrange(data0)
reg_frame.append(gang_nam)

In [0]:
data1 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/강동구.csv', na_values='-')
reg = region[1]

data1 = handling(data1)
gang_dong = arrange(data1)
reg_frame.append(gang_dong)

In [0]:
data2 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/강북구.csv', na_values='-')
reg = region[2]

data2 = handling(data2)
gang_buk = arrange(data2)
reg_frame.append(gang_buk)

In [0]:
data3 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/강서구.csv', na_values='-')
reg = region[3]

data3 = handling(data3)
gang_seo = arrange(data3)
reg_frame.append(gang_seo)

In [0]:
data4 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/관악구.csv', na_values='-')
reg = region[4]

data4 = handling(data4)
gwan_ak = arrange(data4)
reg_frame.append(gwan_ak)

In [0]:
data5 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/광진구.csv', na_values='-')
reg = region[5]

data5 = handling(data5)
gwang_jin = arrange(data5)
reg_frame.append(gwang_jin)

In [0]:
data6 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/구로구.csv', na_values='-')
reg = region[6]

data6 = handling(data6)
gu_ro = arrange(data6)
reg_frame.append(gu_ro)

In [0]:
data7 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/금천구.csv', na_values='-')
reg = region[7]

data7 = handling(data7)
geum_chun = arrange(data7)
reg_frame.append(geum_chun)

In [0]:
data8 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/노원구.csv', na_values='-')
reg = region[8]

data8 = handling(data8)
no_won = arrange(data8)
reg_frame.append(no_won)

In [0]:
data9 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/도봉구.csv', na_values='-')
reg = region[9]

data9 = handling(data9)
do_bong = arrange(data9)
reg_frame.append(do_bong)

In [0]:
data10 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/동대문구.csv', na_values='-')
reg = region[10]

data10 = handling(data10)
dong_dae_mun = arrange(data10)
reg_frame.append(dong_dae_mun)

In [0]:
data11 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/동작구.csv', na_values='-')
reg = region[11]

data11 = handling(data11)
dong_jak = arrange(data11)
reg_frame.append(dong_jak)

In [0]:
data12 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/마포구.csv', na_values='-')
reg = region[12]

data12 = handling(data12)
ma_po= arrange(data12)
reg_frame.append(ma_po)

In [0]:
data13 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/서대문구.csv', na_values='-')
reg = region[13]

data13 = handling(data13)
seo_dae_mun= arrange(data13)
reg_frame.append(seo_dae_mun)

In [0]:
data14 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/서초구.csv', na_values='-')
reg = region[14]

data14 = handling(data14)
seo_cho= arrange(data14)
reg_frame.append(seo_cho)

In [0]:
data15 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/성동구.csv', na_values='-')
reg = region[15]

data15 = handling(data15)
sung_dong= arrange(data15)
reg_frame.append(sung_dong)

In [0]:
data16 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/성북구.csv', na_values='-')
reg = region[16]

data16 = handling(data16)
sung_buk= arrange(data16)
reg_frame.append(sung_buk)

In [0]:
data17 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/송파구.csv', na_values='-')
reg = region[17]

data17 = handling(data17)
song_pa= arrange(data17)
reg_frame.append(song_pa)

In [0]:
data18 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/양천구.csv', na_values='-')
reg = region[18]

data18 = handling(data18)
yang_chun= arrange(data18)
reg_frame.append(yang_chun)

In [0]:
data19 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/영등포구.csv', na_values='-')
reg = region[19]

data19 = handling(data19)
yeong_deung= arrange(data19)
reg_frame.append(yeong_deung)

In [0]:
data20 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/용산구.csv', na_values='-')
reg = region[20]

data20 = handling(data20)
yong_san= arrange(data20)
reg_frame.append(yong_san)

In [0]:
data21 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/은평구.csv', na_values='-')
reg = region[21]

data21 = handling(data21)
eun_pyeong= arrange(data21)
reg_frame.append(eun_pyeong)

In [0]:
data22 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/종로구.csv', na_values='-')
reg = region[22]

data22 = handling(data22)
jong_ro= arrange(data22)
reg_frame.append(jong_ro)

In [0]:
data23 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/중구.csv', na_values='-')
reg = region[23]

data23 = handling(data23)
jung= arrange(data23)
reg_frame.append(jung)

In [0]:
data24 = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/중랑구.csv', na_values='-')
reg = region[24]

data24 = handling(data24)
jung_nang= arrange(data24)
reg_frame.append(jung_nang)

In [0]:
reg_frame[1]

          기간  자치구   승하차 평균
0   2011년01월  강동구      NaN
1   2011년02월  강동구      NaN
2   2011년03월  강동구      NaN
3   2011년04월  강동구      NaN
4   2011년05월  강동구      NaN
5   2011년06월  강동구      NaN
6   2011년07월  강동구      NaN
7   2011년08월  강동구      NaN
8   2011년09월  강동구      NaN
9   2011년10월  강동구      NaN
10  2011년11월  강동구      NaN
11  2011년12월  강동구      NaN
12  2012년01월  강동구  26089.8
13  2012년02월  강동구  28442.3
14  2012년03월  강동구  29262.3
15  2012년04월  강동구  28728.0
16  2012년05월  강동구  29247.7
17  2012년06월  강동구  28260.6
18  2012년07월  강동구  27148.7
19  2012년08월  강동구  25305.5
20  2012년09월  강동구  27066.2
21  2012년10월  강동구  27664.7
22  2012년11월  강동구  29058.8
23  2012년12월  강동구  28472.9
24  2013년01월  강동구  27733.4
25  2013년02월  강동구  27402.1
26  2013년03월  강동구  28827.4
27  2013년04월  강동구  29430.0
28  2013년05월  강동구  29228.1
29  2013년06월  강동구  27565.5
..       ...  ...      ...
66  2016년07월  강동구  25617.1
67  2016년08월  강동구  25031.2
68  2016년09월  강동구  25007.1
69  2016년10월  강동구  26416.9
70  2016년11월  강동구  27306.7
71  2016년12월  강동구  27122.8
72  2017년01월  강동구  24283.5
73  2017년02월  강동구  26776.8
74  2017년03월  강동구  27657.3
75  2017년04월  강동구  27376.5
76  2017년05월  강동구  26559.1
77  2017년06월  강동구  27053.3
78  2017년07월  강동구  25502.2
79  2017년08월  강동구  25132.2
80  2017년09월  강동구  27264.4
81  2017년10월  강동구  23890.6
82  2017년11월  강동구  27571.0
83  2017년12월  강동구  26792.3
84  2018년01월  강동구  25564.2
85  2018년02월  강동구  24724.5
86  2018년03월  강동구  27415.5
87  2018년04월  강동구  27498.6
88  2018년05월  강동구  27343.9
89  2018년06월  강동구  26462.7
90  2018년07월  강동구  26200.1
91  2018년08월  강동구  25107.4
92  2018년09월  강동구  24679.5
93  2018년10월  강동구  27352.7
94  2018년11월  강동구  28177.7
95  2018년12월  강동구  26388.5

[96 rows x 3 columns]

In [0]:
# 데이터 합치기

final_data = pd.concat([reg_frame[0], reg_frame[1]])

for i in range(2, len(region)):
    final_data = pd.concat([final_data, reg_frame[i]])

In [0]:
# 성공!

final_data

          기간  자치구   승하차 평균
0   2011년01월  강남구   9686.9
1   2011년02월  강남구   9022.7
2   2011년03월  강남구  10448.3
3   2011년04월  강남구  10207.6
4   2011년05월  강남구   9677.4
5   2011년06월  강남구   9981.6
6   2011년07월  강남구   9814.0
7   2011년08월  강남구   9461.1
8   2011년09월  강남구   9454.6
9   2011년10월  강남구   9626.1
10  2011년11월  강남구   9927.1
11  2011년12월  강남구   9776.4
12  2012년01월  강남구  59596.4
13  2012년02월  강남구  66080.5
14  2012년03월  강남구  63664.4
15  2012년04월  강남구  61610.5
16  2012년05월  강남구  61937.4
17  2012년06월  강남구  62380.8
18  2012년07월  강남구  63211.5
19  2012년08월  강남구  58396.8
20  2012년09월  강남구  59207.0
21  2012년10월  강남구  58385.0
22  2012년11월  강남구  63001.2
23  2012년12월  강남구  60921.9
24  2013년01월  강남구  47843.8
25  2013년02월  강남구  45876.5
26  2013년03월  강남구  46971.2
27  2013년04월  강남구  48685.5
28  2013년05월  강남구  47446.5
29  2013년06월  강남구  44701.0
..       ...  ...      ...
66  2016년07월  중랑구  23888.4
67  2016년08월  중랑구  23182.9
68  2016년09월  중랑구  23745.9
69  2016년10월  중랑구  24934.6
70  2016년11월  중랑구  25694.4
71  2016년12월  중랑구  25258.6
72  2017년01월  중랑구  22574.7
73  2017년02월  중랑구  24640.1
74  2017년03월  중랑구  25996.6
75  2017년04월  중랑구  25767.6
76  2017년05월  중랑구  25206.9
77  2017년06월  중랑구  25068.3
78  2017년07월  중랑구  23286.0
79  2017년08월  중랑구  23028.6
80  2017년09월  중랑구  25305.3
81  2017년10월  중랑구  22537.6
82  2017년11월  중랑구  25581.6
83  2017년12월  중랑구  24603.9
84  2018년01월  중랑구  23464.3
85  2018년02월  중랑구  23071.7
86  2018년03월  중랑구  25804.7
87  2018년04월  중랑구  25996.4
88  2018년05월  중랑구  26044.6
89  2018년06월  중랑구  24943.7
90  2018년07월  중랑구  24224.4
91  2018년08월  중랑구  23413.6
92  2018년09월  중랑구  23525.6
93  2018년10월  중랑구  25762.0
94  2018년11월  중랑구  26271.0
95  2018년12월  중랑구  24739.7

[2400 rows x 3 columns]

In [0]:
final_data.to_csv('/gdrive/My Drive/문화관광공모전/subway.csv', mode= 'w', sep=',')