In [0]:
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).

In [0]:
import pandas as pd
import numpy as np

In [0]:
tmp = pd.read_csv('/gdrive/My Drive/문화관광공모전/data/유동인구/전철_지하철_역별_이용객수(2011.01~2018.12)(월별_총승하차수_평균)/csv/강남구.csv', na_values='-')
tmp.head()

  검색결과 Unnamed: 1     Unnamed: 2  ... Unnamed: 66 Unnamed: 67 Unnamed: 68
0   구분        NaN            NaN  ...         NaN         NaN         NaN
1  NaN        NaN            NaN  ...         NaN         NaN         NaN
2  호선명         역명           행정구역  ...         토요일         일요일        모든요일
3  2호선         삼성  ___삼성1동(서울강남)  ...       63882      110010      115625
4  2호선         선릉  ___삼성2동(서울강남)  ...       29616      107187      102847

[5 rows x 69 columns]

In [0]:
# 불필요한 부분 자르기

col = list(tmp.iloc[2])
data = tmp.iloc[3:, :]
data.columns = col
data.head()

   호선명   역명           행정구역   월   승하차  ...     목요일     금요일     토요일     일요일    모든요일
3  2호선   삼성  ___삼성1동(서울강남)  1월  총승하차  ...  138180   89601   63882  110010  115625
4  2호선   선릉  ___삼성2동(서울강남)  1월  총승하차  ...  127087   58366   29616  107187  102847
5  2호선   역삼  ___역삼1동(서울강남)  1월  총승하차  ...  125530   51572   30138  105083  101338
6  2호선   강남  ___역삼2동(서울강남)  1월  총승하차  ...  261014  192505  110301  206777  215833
7  3호선  압구정   ___신사동(서울강남)  1월  총승하차  ...   83712   64594   34721   67906   71125

[5 rows x 69 columns]

In [0]:
# 전체 요일만 추려서 연도별로 바꿔주기
# 값들 숫자로 바꿔줘야함

data_col = data[['월', '모든요일']]
data_col.columns = ['월', '2011년', '2012년', '2013년', '2014년', '2015년', '2016년', '2017년', '2018년']
data_col.head()

    월 2011년   2012년 2013년   2014년   2015년   2016년   2017년   2018년
3  1월   NaN  131981   NaN  113998  128274  108826  106401  115625
4  1월   NaN  114279   NaN  100869  107425   99117   94747  102847
5  1월   NaN   97040   NaN   94783  100659   94601   90628  101338
6  1월   NaN  210559   NaN  224847  229775  211807  202083  215833
7  1월   NaN   88574   NaN   79761   82841   73743   68292   71125

In [0]:
# 데이터 타입 바꿔주기

col = list(data_col.columns)
series = [data_col['월']]
for year in col:
    if year != '월':
        series.append(pd.to_numeric(data_col[year]))
        
num_data = pd.concat([series[0], series[1]], axis=1)
for i in range(2, len(series)):
    num_data = pd.concat([num_data, series[i]], axis=1)
num_data.head()

    월  2011년     2012년  2013년     2014년   2015년     2016년     2017년     2018년
3  1월    NaN  131981.0    NaN  113998.0  128274  108826.0  106401.0  115625.0
4  1월    NaN  114279.0    NaN  100869.0  107425   99117.0   94747.0  102847.0
5  1월    NaN   97040.0    NaN   94783.0  100659   94601.0   90628.0  101338.0
6  1월    NaN  210559.0    NaN  224847.0  229775  211807.0  202083.0  215833.0
7  1월    NaN   88574.0    NaN   79761.0   82841   73743.0   68292.0   71125.0

In [0]:
# 월별로 평균내기

int(num_data[num_data['월']=='1월']['2018년'].mean())

56593

In [0]:
months = list(num_data['월'].unique())
num_list = list(range(1, 13))
years = ['2011년', '2012년', '2013년', '2014년', '2015년', '2016년', '2017년', '2018년']
region = ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구']

print(months, years, region)
print(len(months), len(years), len(region))

['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'] ['2011년', '2012년', '2013년', '2014년', '2015년', '2016년', '2017년', '2018년'] ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구', '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구']
12 8 25

In [0]:
num_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [0]:
date = []
district = []
avg_people = []

for year in years:
    for i in range(len(months)):
        avg = int(num_data[num_data['월']==str(num_list[i])+'월'][year].mean()) # 해당 년도, 월의 평균 지하철 이용 수
        reg = region[0]
        
        # 각 리스트에 순차적으로 넣고 데이터 프레임을 만든다.
        date.append("{}{:02d}월".format(year, num_list[i]))
        district.append(reg)
        avg_people.append(avg)

In [0]:
final_data = pd.DataFrame(data={"기간": date, "자치구": district, "총 승하차 수": avg_people}, columns=["기간", "자치구", "총 승하차 수"])
final_data

          기간  자치구  총 승하차 수
0   2011년01월  강남구     9686
1   2011년02월  강남구     9022
2   2011년03월  강남구    10448
3   2011년04월  강남구    10207
4   2011년05월  강남구     9677
5   2011년06월  강남구     9981
6   2011년07월  강남구     9814
7   2011년08월  강남구     9461
8   2011년09월  강남구     9454
9   2011년10월  강남구     9626
10  2011년11월  강남구     9927
11  2011년12월  강남구     9776
12  2012년01월  강남구    59596
13  2012년02월  강남구    66080
14  2012년03월  강남구    63664
15  2012년04월  강남구    61610
16  2012년05월  강남구    61937
17  2012년06월  강남구    62380
18  2012년07월  강남구    63211
19  2012년08월  강남구    58396
20  2012년09월  강남구    59207
21  2012년10월  강남구    58385
22  2012년11월  강남구    63001
23  2012년12월  강남구    60921
24  2013년01월  강남구    47843
25  2013년02월  강남구    45876
26  2013년03월  강남구    46971
27  2013년04월  강남구    48685
28  2013년05월  강남구    47446
29  2013년06월  강남구    44701
..       ...  ...      ...
66  2016년07월  강남구    56655
67  2016년08월  강남구    54402
68  2016년09월  강남구    50876
69  2016년10월  강남구    53922
70  2016년11월  강남구    57501
71  2016년12월  강남구    58149
72  2017년01월  강남구    52908
73  2017년02월  강남구    59023
74  2017년03월  강남구    57757
75  2017년04월  강남구    55423
76  2017년05월  강남구    53008
77  2017년06월  강남구    55817
78  2017년07월  강남구    55436
79  2017년08월  강남구    54028
80  2017년09월  강남구    56403
81  2017년10월  강남구    46746
82  2017년11월  강남구    57716
83  2017년12월  강남구    57224
84  2018년01월  강남구    56593
85  2018년02월  강남구    53441
86  2018년03월  강남구    57450
87  2018년04월  강남구    57081
88  2018년05월  강남구    55606
89  2018년06월  강남구    54975
90  2018년07월  강남구    57877
91  2018년08월  강남구    54882
92  2018년09월  강남구    50395
93  2018년10월  강남구    56373
94  2018년11월  강남구    59701
95  2018년12월  강남구    56961

[96 rows x 3 columns]

In [0]:
avg_people

[9686.857142857143,
 9022.714285714286,
 10448.285714285714,
 10207.57142857143,
 9677.42857142857,
 9981.57142857143,
 9814.0,
 9461.142857142857,
 9454.57142857143,
 9626.142857142857,
 9927.142857142857,
 9776.42857142857,
 59596.41176470588,
 66080.4705882353,
 63664.35294117647,
 61610.529411764706,
 61937.35294117647,
 62380.82352941176,
 63211.470588235294,
 58396.82352941176,
 59207.0,
 58385.0,
 63001.23529411765,
 60921.882352941175,
 47843.75,
 45876.5,
 46971.25,
 48685.5,
 47446.5,
 44701.0,
 45970.5,
 42246.0,
 40799.75,
 46771.0,
 48052.25,
 47022.5,
 57643.41176470588,
 60843.76470588235,
 60336.58823529412,
 61191.35294117647,
 57570.470588235294,
 56988.05882352941,
 62226.705882352944,
 56682.0,
 54957.17647058824,
 58125.35294117647,
 59344.35294117647,
 62658.35294117647,
 44241.555555555555,
 40813.37037037037,
 45213.851851851854,
 44219.77777777778,
 40687.74074074074,
 39445.333333333336,
 42712.444444444445,
 39391.333333333336,
 39418.18518518518,
 41711.0,
 42493.92592592593,
 43888.07407407407,
 55073.117647058825,
 52821.705882352944,
 58034.94117647059,
 56049.294117647056,
 55043.882352941175,
 56060.94117647059,
 56655.58823529412,
 54402.294117647056,
 50876.64705882353,
 53922.82352941176,
 57501.23529411765,
 58149.705882352944,
 52908.82352941176,
 59023.58823529412,
 57757.35294117647,
 55423.76470588235,
 53008.117647058825,
 55817.117647058825,
 55436.23529411765,
 54028.882352941175,
 56403.0,
 46746.0,
 57716.76470588235,
 57224.41176470588,
 56593.470588235294,
 53441.35294117647,
 57450.882352941175,
 57081.705882352944,
 55606.41176470588,
 54975.94117647059,
 57877.41176470588,
 54882.82352941176,
 50395.23529411765,
 56373.882352941175,
 59701.705882352944,
 56961.58823529412]